PROCESS BEFORE OUTPUT.
* Verarbeitung vor der Ausgabe
  MODULE INIT.

  MODULE INIT_9553.

  MODULE PAGE_NUMBERS.
  CALL SUBSCREEN SUBSCREEN_T582C INCLUDING SUBSCR_PROG SUBSCR_DYNNR.
PROCESS AFTER INPUT.
* Verarbeitung nach der Eingabe
  MODULE EXIT AT EXIT-COMMAND.

  MODULE LEAVE.

  FIELD PPHDX-RECORD_NR MODULE SET_RECORD_NR ON REQUEST.

  CHAIN.
    FIELD P9553-OBJID.
    MODULE EXIST_OBJECT  ON CHAIN-REQUEST.
    MODULE FUELLE_BUFFER ON CHAIN-REQUEST.
  ENDCHAIN.

  CHAIN.
    FIELD P9553-BEGDA.
    FIELD P9553-ENDDA.
    MODULE CHECK_DATE.
    MODULE INSERT_OK.
  ENDCHAIN.

* specific processing for infotype P9553
  CHAIN.
    FIELD P9553-OBJID.
    FIELD P9553-BEGDA.
    FIELD P9553-ENDDA.
*   FIELD P9553-SPECIFIC.
    MODULE CHECK_ZB0.
    MODULE INPUT_DONE ON CHAIN-REQUEST.
  ENDCHAIN.
  CALL SUBSCREEN SUBSCREEN_T582C.
*   FIELD P9553-LANGU MODULE NEW_LANGU ON REQUEST.

  MODULE CHECK_MOUSE_CLICK.

  MODULE CHECK_EMPTY.

  MODULE OK-CODE.

PROCESS ON VALUE-REQUEST.
  FIELD P9553-OBJID MODULE OBJID_REQUEST.










