*&---------------------------------------------------------------------*
*& Include          MZCMRK410_SEL
*&---------------------------------------------------------------------*
SELECTION-SCREEN FUNCTION KEY 1.

SELECTION-SCREEN BEGIN OF BLOCK bl1 WITH FRAME TITLE TEXT-b01.

  SELECTION-SCREEN BEGIN OF LINE.
    SELECTION-SCREEN COMMENT (31) TEXT-002.

    PARAMETERS r1 RADIOBUTTON GROUP g1 DEFAULT 'X' USER-COMMAND rr1.
    SELECTION-SCREEN COMMENT (10) FOR FIELD r1  MODIF ID cmt.

    PARAMETERS r2 RADIOBUTTON GROUP g1.
    SELECTION-SCREEN COMMENT (10) FOR FIELD r2  MODIF ID cmt.

  SELECTION-SCREEN END OF LINE.
  SELECTION-SCREEN SKIP 1.

  PARAMETERS: p_orgcd LIKE hrp1000-objid OBLIGATORY DEFAULT '30000002'
                        AS LISTBOX VISIBLE LENGTH 25.

  PARAMETERS: p_peryr LIKE piqstregper-peryr OBLIGATORY USER-COMMAND pp
                        AS LISTBOX VISIBLE LENGTH 25.

  PARAMETERS: p_perid LIKE piqstregper-perid OBLIGATORY USER-COMMAND pp
                        AS LISTBOX VISIBLE LENGTH 25.


  SELECTION-SCREEN SKIP 1.

  SELECTION-SCREEN BEGIN OF LINE.
    PARAMETERS: p_type1 RADIOBUTTON GROUP gp2 DEFAULT 'X' "엑셀업로드
                                     USER-COMMAND  uc1.
    SELECTION-SCREEN COMMENT (10)  FOR FIELD p_type1.
  SELECTION-SCREEN END OF LINE.

  PARAMETERS p_ufile LIKE rlgrap-filename. "OBLIGATORY.
  SELECTION-SCREEN SKIP 1.

  SELECTION-SCREEN BEGIN OF LINE.
    PARAMETERS: p_type2 RADIOBUTTON GROUP gp2. "직접입력
    SELECTION-SCREEN COMMENT (10)  FOR FIELD p_type2.
  SELECTION-SCREEN END OF LINE.

  PARAMETERS p_se LIKE hrp1000-short. "분반.
  SELECT-OPTIONS: p_stnum FOR cmacbpst-student12 NO INTERVALS. "학번.

SELECTION-SCREEN END OF BLOCK bl1.

AT SELECTION-SCREEN ON VALUE-REQUEST FOR p_ufile.
  PERFORM get_file.

AT SELECTION-SCREEN ON VALUE-REQUEST FOR p_orgcd.
  PERFORM org_f4_entry.

AT SELECTION-SCREEN.
  PERFORM screen_ucomm.

AT SELECTION-SCREEN OUTPUT.
  PERFORM modify_screen.
  PERFORM get_datum.
