*&---------------------------------------------------------------------*
*&  SELECTION-SCREEN
*&---------------------------------------------------------------------*
SELECTION-SCREEN FUNCTION KEY 1.
SELECTION-SCREEN FUNCTION KEY 2.
SELECTION-SCREEN FUNCTION KEY 3.
SELECTION-SCREEN FUNCTION KEY 4.
SELECTION-SCREEN FUNCTION KEY 5.

SELECTION-SCREEN BEGIN OF BLOCK bl1 WITH FRAME TITLE TEXT-b01.

SELECTION-SCREEN BEGIN OF LINE.
SELECTION-SCREEN POSITION 33.
PARAMETERS: p_quota RADIOBUTTON GROUP gp2 USER-COMMAND uc2 DEFAULT 'X'.
SELECTION-SCREEN COMMENT (8)  FOR FIELD p_quota.
PARAMETERS: p_limit RADIOBUTTON GROUP gp2.
SELECTION-SCREEN COMMENT (8)  FOR FIELD p_limit.
SELECTION-SCREEN END OF LINE.

PARAMETERS: p_orgcd LIKE hrp1000-objid OBLIGATORY DEFAULT '30000002'
                      AS LISTBOX VISIBLE LENGTH 30.

PARAMETERS: p_peryr LIKE piqstregper-peryr OBLIGATORY
                      AS LISTBOX VISIBLE LENGTH 30.
PARAMETERS: p_perid LIKE piqstregper-perid OBLIGATORY
                      AS LISTBOX VISIBLE LENGTH 30.

*PARAMETERS: p_begda LIKE hrp1000-begda OBLIGATORY.
*PARAMETERS: p_endda LIKE hrp1000-endda OBLIGATORY.
*SELECTION-SCREEN SKIP 1.

SELECT-OPTIONS: p_smnum FOR hrp1000-short NO INTERVALS.
SELECT-OPTIONS: p_senum FOR hrp1000-short NO INTERVALS.

*SELECTION-SCREEN SKIP 1.

SELECTION-SCREEN END OF BLOCK bl1.
SELECTION-SCREEN SKIP 1.
SELECTION-SCREEN COMMENT 1(80) t_001.
SELECTION-SCREEN SKIP 1.
SELECTION-SCREEN COMMENT 1(80) t_002.
SELECTION-SCREEN SKIP 1.
SELECTION-SCREEN COMMENT 1(80) t_003.
SELECTION-SCREEN SKIP 1.
SELECTION-SCREEN COMMENT 1(80) t_004.
SELECTION-SCREEN SKIP 1.
SELECTION-SCREEN COMMENT 1(80) t_005.
