PROCESS BEFORE OUTPUT.
  MODULE status_0200.
  CALL SUBSCREEN sub210 INCLUDING sy-cprog '0210'.
*
PROCESS AFTER INPUT.
  MODULE exit AT EXIT-COMMAND.

  CALL SUBSCREEN sub210.
  MODULE user_command_0200.
