*&---------------------------------------------------------------------*
*&  SELECTION-SCREEN
*&---------------------------------------------------------------------*
SELECTION-SCREEN FUNCTION KEY 1.
SELECTION-SCREEN FUNCTION KEY 2.
SELECTION-SCREEN FUNCTION KEY 3.
SELECTION-SCREEN FUNCTION KEY 4.
SELECTION-SCREEN FUNCTION KEY 5.

SELECTION-SCREEN BEGIN OF BLOCK bl1 WITH FRAME TITLE TEXT-b01.

PARAMETERS: p_orgcd LIKE hrp1000-objid     OBLIGATORY
                      AS LISTBOX VISIBLE LENGTH 30.
PARAMETERS: p_peryr LIKE piqstregper-peryr OBLIGATORY
                      AS LISTBOX VISIBLE LENGTH 30.
PARAMETERS: p_perid LIKE piqstregper-perid OBLIGATORY
                      AS LISTBOX VISIBLE LENGTH 30.
SELECT-OPTIONS : p_stnum FOR hrp1000-short NO INTERVALS.

SELECTION-SCREEN SKIP 1.

PARAMETERS: p_sel1 RADIOBUTTON GROUP gp1 DEFAULT 'X' USER-COMMAND uc.
PARAMETERS: p_sel2 RADIOBUTTON GROUP gp1.

SELECTION-SCREEN SKIP 1.
PARAMETERS: p_titel AS CHECKBOX DEFAULT 'X'.
PARAMETERS: p_error AS CHECKBOX DEFAULT 'X'.

SELECTION-SCREEN END OF BLOCK bl1.

*SELECTION-SCREEN SKIP 1.
*SELECTION-SCREEN COMMENT 1(83) t_001.
SELECTION-SCREEN SKIP 1.
SELECTION-SCREEN COMMENT 1(83) t_002.
SELECTION-SCREEN SKIP 1.
SELECTION-SCREEN COMMENT 1(83) t_003.
SELECTION-SCREEN SKIP 1.
SELECTION-SCREEN COMMENT 1(83) t_005.
SELECTION-SCREEN SKIP 1.
SELECTION-SCREEN COMMENT 1(83) t_004.
