PROCESS BEFORE OUTPUT.
  MODULE status_0300.
  CALL SUBSCREEN sub310 INCLUDING sy-cprog '0310'.
*
PROCESS AFTER INPUT.
  MODULE exit AT EXIT-COMMAND.

  CALL SUBSCREEN sub310.
  MODULE user_command_0300.
