*&---------------------------------------------------------------------*
*& Include          ZCMRK255_SEL
*&---------------------------------------------------------------------*

*&---------------------------------------------------------------------*
*&  SELECTION-SCREEN
*&---------------------------------------------------------------------*
SELECTION-SCREEN FUNCTION KEY 1.
SELECTION-SCREEN FUNCTION KEY 2.
SELECTION-SCREEN FUNCTION KEY 3.

SELECTION-SCREEN BEGIN OF BLOCK bl1 WITH FRAME TITLE TEXT-b01.

  SELECTION-SCREEN BEGIN OF LINE.
    PARAMETERS: p_stp1 RADIOBUTTON GROUP gp1 DEFAULT 'X' USER-COMMAND uc.
    SELECTION-SCREEN COMMENT (11)  FOR FIELD p_stp1.
    PARAMETERS: p_stp2 RADIOBUTTON GROUP gp1.
    SELECTION-SCREEN COMMENT (11)  FOR FIELD p_stp2.
    PARAMETERS: p_stp3 RADIOBUTTON GROUP gp1.
    SELECTION-SCREEN COMMENT (11)  FOR FIELD p_stp3.
  SELECTION-SCREEN END OF LINE.

  SELECTION-SCREEN SKIP 1.

  PARAMETERS: p_peryr LIKE piqstregper-peryr OBLIGATORY
                        AS LISTBOX VISIBLE LENGTH 25.

  PARAMETERS: p_perid LIKE piqstregper-perid OBLIGATORY
                        AS LISTBOX VISIBLE LENGTH 25 USER-COMMAND uc.

  SELECT-OPTIONS: p_smnum FOR hrp1000-short NO INTERVALS.
  SELECT-OPTIONS: p_stnum FOR hrp1000-short NO INTERVALS.

SELECTION-SCREEN END OF BLOCK bl1.

SELECTION-SCREEN SKIP 1.
SELECTION-SCREEN COMMENT 1(80) t_001.
SELECTION-SCREEN SKIP 1.
SELECTION-SCREEN COMMENT 1(80) t_002.
SELECTION-SCREEN SKIP 1.
SELECTION-SCREEN COMMENT 1(80) t_003.
SELECTION-SCREEN SKIP 1.
SELECTION-SCREEN COMMENT 1(80) t_004.
SELECTION-SCREEN SKIP 1.
SELECTION-SCREEN COMMENT 1(80) t_005.
